services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8081:5173"            # http://localhost:5173
      - "8082:8082"
      - "8080:8080"
    environment:
      HOST: "0.0.0.0"
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    # 기존 command를 entrypoint로 대체(라우트 추가 후 exec로 실제 명령 실행)
    entrypoint:
      - sh
      - -c
      - |
        /app/tools/entrypoint.sh
    volumes:
      - .:/app:delegated       # 로컬 코드를 컨테이너에 마운트
      - node_modules:/app/node_modules  # node_modules는 컨테이너 전용 볼륨
    cap_add:
      - NET_ADMIN     # 컨테이너에서 라우트 추가 권한 부여
    user: root        # 라우트 추가를 위해 root로 실행 (개발용)
    # (리눅스에서 권한 이슈 시 아래 UID/GID 주석 해제, 쉘에서 export UID=$(id -u) GID=$(id -g))
    # user: "${UID:-1000}:${GID:-1000}"

volumes:
  node_modules:
