version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8081:5173"            # http://localhost:5173
    environment:
      HOST: "0.0.0.0"
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    # 기존 command를 entrypoint로 대체(라우트 추가 후 exec로 실제 명령 실행)
    entrypoint:
      - sh
      - -c
      - |
        # 컨테이너의 기본 게이트웨이를 찾아서(예: 172.17.0.1) 라우트 추가
        GATEWAY="$(ip route | awk '/default/ {print $3; exit}')";
        echo "detected gateway: ${GATEWAY}";
        ip route add 192.168.123.0/24 via "${GATEWAY}" dev eth0 || true;
        # 이후 원래 실행하던 명령 실행 (exec로 PID1에 바인딩)
        exec npm run dev -- --host 0.0.0.0 --port 5173
    volumes:
      - .:/app:delegated       # 로컬 코드를 컨테이너에 마운트
      - node_modules:/app/node_modules  # node_modules는 컨테이너 전용 볼륨
    cap_add:
      - NET_ADMIN     # 컨테이너에서 라우트 추가 권한 부여
    user: root        # 라우트 추가를 위해 root로 실행 (개발용)
    # (리눅스에서 권한 이슈 시 아래 UID/GID 주석 해제, 쉘에서 export UID=$(id -u) GID=$(id -g))
    # user: "${UID:-1000}:${GID:-1000}"

volumes:
  node_modules:
