services:
  field_management:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8081:5173"
      - "8082:8082"
      - "8080:8080"
    user: "root"
    environment:
      HOST: "0.0.0.0"
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    volumes:
      - .:/app
      - node_modules:/app/node_modules

  # update_map:
  #   build:
  #     context: ./public/maps
  #   dockerfile: dockerfile.update_map
  #   run: 
volumes:
  node_modules:
